### ISSUE TITLE
Too claustrophobic

### ISSUE THREAD

**Issue by Slinta** [Michal-MK/Unity-Game#2]
You can't see anything and feel helpless in this game. I suggest making a minimap or zooming the camera out a bit. That would only be a temporary solution, because you might lose the effect you're going for. Once there are more rooms in the game, you'll need a minimap anyway.

**Comment by Michal-MK** [comment]
Better guiding system had been implemented as well as a complete overhaul of the starting room.
- now it should be easier to follow the game.
- I do not think that minimap is necessary for a game of this scale.
